### ISSUE TITLE
Trouble with channels count

### ISSUE THREAD

**Issue by ReyRom** [meckbaig/smart-yt-subscriptions#3]
The number of channels in a folder is displayed incorrectly

![image](https://github.com/user-attachments/assets/bbcf8958-6904-4350-bae1-74d4deeed947)

![image](https://github.com/user-attachments/assets/f71252a9-8f23-41fc-850b-75e69b56f742)

**Comment by meckbaig** [comment]
Already solved, see [this](https://github.com/meckbaig/SytsBackendGen2/commit/5c828b919733f2fcd01be001c1e2595ca267fac5) commit
